// This file is part of the course TPV2@UCM - Samir Genaim


#pragma once

// Components list - must have at least one element
//
#define _CMPS_LIST_ \
	TRANSFORM, \
	IMAGE, \
	KEYBOARDPLAYERCTRL, \
	MOVEMENTCONTROLLER, \
    SIMPLEMOVE, \
    HEALTH,\
	LIFETIMETIMER, \
    BULLETDATA, \
    WEAPON, \
	MANA, \
	DECK, \
	CAMERA, \
	CAMERA_FOLLOW, \
	CAMERA_CLAMP, \
	WAVEMANAGER, \
	ENEMYSTATEMACHINE, \
	RENDER_ORDERING, \
    BUTTON,\
	RECT, \
	DYN_IMAGE, \
	OFFSET_DYN_IMAGE, \
	RIGIDBODY, \
	COLLISIONABLE, \
	STATEMACHINE, \
	CONTACT_MANIFOLD, \
	TRIGGER_MANIFOLD, \
	PLAYER_HUD, \
	GENERAL_HUD, \
	TRANSFORMLESS_DYN_IMAGE, \
	MYTHICCOMPONENT,\
	BULLET_COLLISION_COMPONENT, \
	FOG, \
	PLAYER_TRIGGERER, \
	ENEMY_TRIGGERER, \
	ID_COMPONENT,\
	COLLISION_REGISTRATION_BY_ID,\
	REWARDDATACOMPONENT



// Groups list - must have at least one element
//
#define _GRPS_LIST_ \
	BULLET,\
	PLAYER,\
	UI,\
    WEAPONBUTTON, \
    DECKBUTTON,\
    DECKINFO,\
    WEAPONINFO,\
	ENEMY,\
	PLAYERBULLETS,\
    ENEMYBULLETS,\
	STAR_DROP, \
    REWARDCARDS,\
    REWARDDECK, \
    REWARDHEALTH

// Scene list
//
#define _SCENE_LIST_ \
	GAMESCENE,\
	MAINMENUSCENE,\
	CONTROLSSCENE,\
	SELECTIONMENUSCENE,\
	GAMEOVERSCENE,\
	REWARDSCENE

// Handlers list - must have at least one element
//
#define _HDLRS_LIST_ \
    PLAYER, \
    WAVE, \
	GAMEINFO, \
	CAMERA, \
	FOGGROUP, \
	HUD_ENTITY

